CREATE TABLE LOCATION (
    LocationID VARCHAR(10) PRIMARY KEY,
    City VARCHAR(100) NOT NULL
);

CREATE TABLE DEPARTMENT (
    DepartmentCode VARCHAR(10) PRIMARY KEY,
    DepartmentName VARCHAR(100) NOT NULL,
    LocationID VARCHAR(10) NOT NULL,
    FOREIGN KEY (LocationID) REFERENCES LOCATION(LocationID)
);

CREATE TABLE EMPLOYEE (
    EmployeeID VARCHAR(10) PRIMARY KEY,
    EmployeeName VARCHAR(100) NOT NULL,
    EmployeeEmail VARCHAR(100) NOT NULL UNIQUE,
    JobTitle VARCHAR(100) NOT NULL,
    Salary DECIMAL(10,2) NOT NULL,
    HireDate DATE NOT NULL,
    DepartmentCode VARCHAR(10) NOT NULL,
    FOREIGN KEY (DepartmentCode) REFERENCES DEPARTMENT(DepartmentCode)
);